name: Build for macOS

on:
  workflow_dispatch:

jobs:
  build-macos:
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: arm64
          - os: macos-15-intel
            arch: x64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Fail if branch is not main
        if: github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/master'
        run: |
          echo "This workflow should not be triggered with workflow_dispatch on a branch other than main"
          exit 1

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Cache NodeJS modules
        uses: actions/cache@v4
        with:
          path: |
            ./node_modules
            ./app/node_modules
          key: ${{ matrix.os }}-${{ runner.arch }}-deps-${{ hashFiles('yarn.lock') }}-${{ hashFiles('app/package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      - name: Setup Codesigning
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.APPLE_CODESIGN_P12 }}
          p12-password: ${{ secrets.APPLE_CODESIGN_KEY_PASSWORD }}

      # This is disabled because we need to codesign UnifyMail with this profile, but it's
      # presence makes Apple use it for the mailsync executable too. We need more nuanced
      # provisioning profile configuration.
      #
      # - name: Setup Provisioning Profile
      #   run: |
      #     echo "APPLE_PROVISIONING_PROFILE_PATH=${{ runner.temp }}/UnifyMail.provisionprofile" >> $GITHUB_ENV
      #     echo $APPLE_PROVISIONING_PROFILE_B64 | base64 --decode > "${{ runner.temp }}/UnifyMail.provisionprofile"
      #   env:
      #     APPLE_PROVISIONING_PROFILE_B64: ${{ secrets.APPLE_PROVISIONING_PROFILE_B64 }}



      - name: Lint
        run: npm run lint

      - name: Build
        run: SIGN_BUILD=true DEBUG=electron-packager,electron-osx-sign,electron-notarize* npm run build
        env:
          APPLE_ID_ASC_PROVIDER: ${{ secrets.APPLE_ID_ASC_PROVIDER }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_PROVISIONING_PROFILE_PATH: ${{ env.APPLE_PROVISIONING_PROFILE_PATH }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_ID: ${{ secrets.APPLE_ID }}

      - name: Rename artifacts
        if: matrix.os == 'macos-latest'
        run: |
          mv app/dist/UnifyMail.zip app/dist/UnifyMail-AppleSilicon.zip

      - name: Generate latest-mac.yml
        run: node app/build/generate-latest-mac-yml.js
        env:
          ARCH: ${{ matrix.arch }}

      - name: Create/Update Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_number }}
          name: Build ${{ github.run_number }}
          draft: true
          files: |
            app/dist/*.zip
            app/dist/latest-mac.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
